https://www.learn-sudoku.com/x-wing.html

* loop through rows
* loop thorugh numbers
* find number that appears only twice in possibilities
* see if the number exists also in two columns down the same rows. If so, the results must be in the same row
* check that the second row only has that number has possible in those two cells
* remove that number from possible in the same column
* repeat looping through rows

In [1]:
import numpy as np
from baseNaked234Hidden234 import *

In [2]:
# cells [2,1], [2,3], [4,1], [4,3] = 4
xwingSudoku = np.zeros((9,9))
xwingSudoku[0,2] = 3
xwingSudoku[0,3] = 8
xwingSudoku[0,6] = 5
xwingSudoku[0,7] = 1
xwingSudoku[1,2] = 8
xwingSudoku[1,3] = 7
xwingSudoku[1,6] = 9
xwingSudoku[1,7] = 3
xwingSudoku[2,0] = 1
xwingSudoku[2,3] = 3
xwingSudoku[2,5] = 5
xwingSudoku[2,6] = 7
xwingSudoku[2,7] = 2
xwingSudoku[2,8] = 8
xwingSudoku[3,3] = 2
xwingSudoku[3,6] = 8
xwingSudoku[3,7] = 4
xwingSudoku[3,8] = 9
xwingSudoku[4,0] = 8
xwingSudoku[4,2] = 1
xwingSudoku[4,3] = 9
xwingSudoku[4,5] = 6
xwingSudoku[4,6] = 2
xwingSudoku[4,7] = 5
xwingSudoku[4,8] = 7
xwingSudoku[5,3] = 5
xwingSudoku[5,6] = 1
xwingSudoku[5,7] = 6
xwingSudoku[5,8] = 3
xwingSudoku[6,0] = 9
xwingSudoku[6,1] = 6
xwingSudoku[6,2] = 4
xwingSudoku[6,3] = 1
xwingSudoku[6,4] = 2
xwingSudoku[6,5] = 7
xwingSudoku[6,6] = 3
xwingSudoku[6,7] = 8
xwingSudoku[6,8] = 5
xwingSudoku[7,0] = 3
xwingSudoku[7,1] = 8
xwingSudoku[7,2] = 2
xwingSudoku[7,3] = 6
xwingSudoku[7,4] = 5
xwingSudoku[7,5] = 9
xwingSudoku[7,6] = 4
xwingSudoku[7,7] = 7
xwingSudoku[7,8] = 1
xwingSudoku[8,1] = 1
xwingSudoku[8,3] = 4
xwingSudoku[8,6] = 6
xwingSudoku[8,7] = 9
xwingSudoku[8,8] = 2

In [3]:
def checkXwingsRows(ns):
    m, s = getMapping()
    # loop through rows
    candidateRow = []            
    candidateNum = []
    candidateCol = []            
    for rowIdx in range(0,9):
        idxs = getIdxs(rowIdx, 'row')
        for thisNum in range(1,10):
            nCount = 0
            okRow = rowIdx
            okCol = []
            for colIdx in range(0,9):
                nsIdx = m[rowIdx, colIdx]
                p = ns[nsIdx]
                if thisNum in p:
                    nCount = nCount + 1
                    okCol.append(colIdx)
            if nCount == 2:
                candidateNum.append(thisNum)
                candidateRow.append(okRow)
                candidateCol.append(okCol)
            
    #verify x-wings
    xwings = []
    idxs = []
    for i in range(0, len(candidateNum)-1):
        num1 = candidateNum[i]
        cols1 = candidateCol[i]
        row1 = candidateRow[i]
        for ii in range(i+1, len(candidateNum)):
            num2 = candidateNum[ii]
            cols2 = candidateCol[ii]
            row2 = candidateRow[ii]
        #check that the num and the cols are he same
            if num1 == num2 and cols1 == cols2:
                xwings.append(num1)
                idxs.append([[row1, row2], cols1])
    return(xwings, idxs)


# now we remove all those numbers from the other rows in the columns where they appear
def replaceXwingsRows(ns, xwings, idxs):
    if len(xwings) == 0:
        return(ns)
    for i in range(0, len(xwings)):
        thisNum = xwings[i]
        #idxs of the first of the two cols
        idx1 = getIdxs(idxs[i][1][0], 'col')
        idx2 = getIdxs(idxs[i][1][1], 'col')
        idx3 = getIdxs(idxs[i][0][0], 'row')
        idx4 = getIdxs(idxs[i][0][1], 'row')
        allColsIdx = idx1 + idx2
        allRowsIdx = idx3 + idx4
        #remove row idx from col idx:
        allIdxs = remove_values_from_list(allColsIdx, allRowsIdx)
        for i in allIdxs:
            ns[i] = remove_values_from_list(ns[i], [thisNum])
    return(ns)

def solveXwingsRows(ns):
    xwings, idxs = checkXwingsRows(ns)
    ns = replaceXwingsRows(ns, xwings, idxs)
    return(ns)

In [4]:
ns = getPossibilities(xwingSudoku)
print(ns[1])
print(ns[19])
p = solveXwingsRows(ns)
print(p[1])
print(p[19])


[2, 4, 7, 9]
[4, 9]
[2, 7, 9]
[4, 9]


In [5]:
def checkXwingsCols(ns):
    m, s = getMapping()
    # loop through rows
    candidateRow = []            
    candidateNum = []
    candidateCol = []            
    for colIdx in range(0,9):
        idxs = getIdxs(colIdx, 'col')
        for thisNum in range(1,10):
            nCount = 0
            okCol = colIdx
            okRow = []
            for rowIdx in range(0,9):
                nsIdx = m[rowIdx, colIdx]
                p = ns[nsIdx]
                if thisNum in p:
                    nCount = nCount + 1
                    okRow.append(rowIdx)
            if nCount == 2:
                candidateNum.append(thisNum)
                candidateRow.append(okRow)
                candidateCol.append(okCol)
            
    #verify x-wings
    xwings = []
    idxs = []
    for i in range(0, len(candidateNum)-1):
        num1 = candidateNum[i]
        col1 = candidateCol[i]
        rows1 = candidateRow[i]
        for ii in range(i+1, len(candidateNum)):
            num2 = candidateNum[ii]
            col2 = candidateCol[ii]
            rows2 = candidateRow[ii]
        #check that the num and the cols are he same
            if num1 == num2 and rows1 == rows2:
                xwings.append(num1)
                idxs.append([rows1, [col1, col2]])
    return(xwings, idxs)


# now we remove all those numbers from the other rows in the columns where they appear
def replaceXwingsCols(ns, xwings, idxs):
    if len(xwings) == 0:
        return(ns)
    for i in range(0, len(xwings)):
        thisNum = xwings[i]
        #idxs of the first of the two cols
        idx1 = getIdxs(idxs[i][1][0], 'col')
        idx2 = getIdxs(idxs[i][1][1], 'col')
        idx3 = getIdxs(idxs[i][0][0], 'row')
        idx4 = getIdxs(idxs[i][0][1], 'row')
        allColsIdx = idx1 + idx2
        allRowsIdx = idx3 + idx4
        #remove row idx from col idx:
        allIdxs = remove_values_from_list(allRowsIdx, allColsIdx)
        for i in allIdxs:
            ns[i] = remove_values_from_list(ns[i], [thisNum])
    return(ns)

def solveXWingsCols(ns):
    xwings, idxs = checkXwingsCols(ns)
    ns = replaceXwingsCols(ns, xwings, idxs)
    return(ns)

should try to collapse rows and cols solver into just 2 functions

In [6]:
def solveXwings(ns):
    xwings, idxs = checkXwingsRows(ns)
    ns = replaceXwingsCols(ns, xwings, idxs)
    xwings, idxs = checkXwingsCols(ns)
    ns = replaceXwingsCols(ns, xwings, idxs)
    return(ns)


In [12]:
# ns = getPossibilities(xwingSudoku)
print(ns)
p = solveXwings(ns)
#print(p)

p = solveNakedPairs(ns)
#print(p)               
p = solveNaked3(ns)
print(p)
print(fillGridFromPoss(xwingSudoku, p))
print(getPossibilities(fillGridFromPoss(xwingSudoku, p)))
p = solveNaked4(ns)
#print(p)
p = solveHiddenPairs(ns)
#print(p)
p = solveHidden3(ns)
#print(p)
p = solveHidden4(ns)
#print(p)
p = solveXwings(ns)
#print(p)
        
# from sudokuSamples import *
# b = solveSudoku(sampleSudoku)
# print(b[0])
# ns = getPossibilities(b[0])
# print(ns)
# p = solveXwings(ns)
# print(p)
# print(p == ns)

[[], [2, 9], [3], [8], [6, 9], [2, 4], [5], [1], [4, 6], [], [2, 5], [8], [7], [1, 6], [2, 4], [9], [3], [4, 6], [1], [], [], [3], [], [5], [7], [2], [8], [], [], [], [2], [], [], [8], [4], [9], [8], [3, 4], [1], [9], [4], [6], [2], [5], [7], [2, 4], [2, 9], [9], [5], [8], [8], [1], [6], [3], [9], [6], [4], [1], [2], [7], [3], [8], [5], [3], [8], [2], [6], [5], [9], [4], [7], [1], [], [1], [], [4], [], [], [6], [9], [2]]
[[], [2, 9], [3], [8], [6, 9], [2, 4], [5], [1], [4, 6], [], [5], [8], [7], [1, 6], [2, 4], [9], [3], [4, 6], [1], [], [], [3], [], [5], [7], [2], [8], [], [], [], [2], [], [], [8], [4], [9], [8], [3, 4], [1], [9], [4], [6], [2], [5], [7], [2, 4], [2, 9], [9], [5], [8], [8], [1], [6], [3], [9], [6], [4], [1], [2], [7], [3], [8], [5], [3], [8], [2], [6], [5], [9], [4], [7], [1], [], [1], [], [4], [], [], [6], [9], [2]]
[[0. 0. 3. 8. 0. 0. 5. 1. 0.]
 [0. 5. 8. 7. 0. 0. 9. 3. 0.]
 [1. 0. 0. 3. 0. 5. 7. 2. 8.]
 [0. 0. 0. 2. 0. 0. 8. 4. 9.]
 [8. 0. 1. 9. 4. 6. 2. 5. 7.]
 [0

In [20]:
print(np.array_equal(xwingSudoku, np.zeros((9,9))))

False
