https://www.learn-sudoku.com/xy-wing.html

In [1]:
import numpy as np
from itertools import combinations
from baseNaked234Hidden234Xwing import *

In [2]:
# xy wing in [2,0], [2,3], [0,5] = 1, 7, 2
xywingSudoku = np.zeros((9,9))
xywingSudoku[0,1] = 4
xywingSudoku[0,3] = 5
xywingSudoku[0,4] = 9
xywingSudoku[1,0] = 5
xywingSudoku[1,1] = 9
xywingSudoku[1,2] = 7
xywingSudoku[1,4] = 8
xywingSudoku[2,1] = 6
xywingSudoku[2,2] = 8
xywingSudoku[2,4] = 3
xywingSudoku[2,5] = 4
xywingSudoku[3,2] = 2
xywingSudoku[4,5] = 2
xywingSudoku[0,6] = 6
xywingSudoku[3,3] = 1

In [3]:
# find the 3 cells
# 3 numbers in common
# each cell has only 2 numbers
# each cell share only one umber with the other two
# only one of the 3 intercet both the other two
#list(np.unique(np.asarray([3,4] + [8,4])))
# first just look for 3 cells tht could be a xy wing, we worry about intersection later

def checkForXywing(ns):
    comb = list(combinations(list(range(0,81)), 3))
    posAre = []
    for thisComb in comb:
        num1 = ns[thisComb[0]]
        num2 = ns[thisComb[1]]
        num3 = ns[thisComb[2]]
        if len(num1) == 2 and len(num2) == 2 and len(num3) ==2:
            int1 = list(np.unique(np.asarray(num1 + num2)))
            int2 = list(np.unique(np.asarray(num2 + num3)))
            int3 = list(np.unique(np.asarray(num1 + num3)))
            allInt = list(np.unique(np.asarray(int1 + int2 + int3)))
            if len(int1) == 3 and len(int2) == 3 and len(int3) == 3 and len(allInt) == 3:
                posAre.append(thisComb)

    #now we validate positions
    #this is wrong
    okPos = []
    okVert = []
    okWings = []
    for thisCandidates in posAre:
        countApp = []
        for thisIdx in thisCandidates:
            allInts = getIntersections(thisIdx)
            countApp.append(len(intersection(allInts, list(thisCandidates))))
        if len(intersection(countApp, [3])) == 1:
            okPos.append(thisCandidates)
            okVert.append(findIdx(countApp, 3))
            okWings.append(negFindIdx(countApp, 3))
    return(okPos, okVert, okWings)

# all intersections for a given 0-80 IDX
def getIntersections(idx):
    m, s = getMapping()
    rowCol = np.ndarray.tolist(np.argwhere(m == idx))
    ints = [np.ndarray.tolist(m[rowCol[0][0],:]) +  np.ndarray.tolist(m[:,rowCol[0][1]])][0]
    for i in range(0,9):
        idxS = getIdxs(i, 'square')
        if idx in idxS:
            ints = ints + idxS
    ints = np.ndarray.tolist(np.unique(np.asarray(ints)))
    return(ints)

def findIdx(lst, a):
    return [i for i, x in enumerate(lst) if x==a]

def negFindIdx(lst, a):
    return [i for i, x in enumerate(lst) if not x==a]

# do replacements
def replaceXywing(ns, pos, verts, wings):
    if len(pos) == 0:
        return(ns)
    for i in range(0, len(pos)):
        thisSet = list(pos[i])
        thisVert = verts[i]
        thisWings = wings[i]
        lst1 = getIntersections(pos[0][thisWings[0]])
        lst2 = getIntersections(pos[0][thisWings[1]])
        tmpLst = intersection(lst1, lst2)
        toRemove = intersection(ns[pos[0][thisWings[0]]], ns[pos[0][thisWings[1]]])[0]
        for ii in tmpLst:
            thisNs = ns[ii]
            if len(thisNs)>1 and toRemove in thisNs:
                thisNs.remove(toRemove)
            ns[ii] = thisNs
    return(ns)


def solevXYwing(ns):
    pos, vert, wings = checkForXywing(ns)
    ns = replaceXywing(ns, pos, vert, wings)
    return(ns)


In [4]:
print(xywingSudoku)
ns = getPossibilities(xywingSudoku)
ns = solevXYwing(ns)
grid = fillGridFromPoss(xywingSudoku, ns)
print(grid)

[[0. 4. 0. 5. 9. 0. 6. 0. 0.]
 [5. 9. 7. 0. 8. 0. 0. 0. 0.]
 [0. 6. 8. 0. 3. 4. 0. 0. 0.]
 [0. 0. 2. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 2. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 4. 3. 5. 9. 0. 6. 0. 0.]
 [5. 9. 7. 0. 8. 0. 0. 0. 0.]
 [0. 6. 8. 0. 3. 4. 0. 0. 0.]
 [0. 0. 2. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 2. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
